/**
 * FORGE 2.0 — DesignTokenManager (UI Engine).
 *
 * Ensures every project FORGE builds shares one consistent, world-class default design token
 * set (colors, typography, spacing, border radius, shadows, breakpoints) expressed as Tailwind
 * CSS custom properties — the same `--primary`/`--secondary`/`--background` etc. variable names
 * shadcn/ui's own generated components reference — so a component generated by
 * {@link "./component-generator.js".UIComponentGenerator} always resolves to a real, themed
 * color rather than an undefined CSS variable.
 *
 * House style, matching `component-generator.ts`/`shadcn-installer.ts`: detection
 * (`detectProjectTokens`) degrades silently on a missing/unparseable file — a project with no
 * existing tokens yet is the common case, not an error. `ensureDesignTokens` never overwrites a
 * project's own `tailwind.config.ts`/`globals.css` once either already exists; it only writes
 * when neither is present, so a project that already configured its own tokens is left alone.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { logLine } from '../tools/forge-logger.js';

// ---------------------------------------------------------------------------
// Public contract
// ---------------------------------------------------------------------------

/** The full set of design tokens shared across every project FORGE builds. */
export interface DesignTokens {
  /** Semantic color tokens, keyed by Tailwind CSS variable name without the leading `--`. */
  colors: Record<string, string>;
  /** Typography tokens (font family, base sizes, weights, line-heights). */
  typography: Record<string, string>;
  /** Spacing scale tokens, keyed by Tailwind scale step. */
  spacing: Record<string, string>;
  /** Border radius tokens, keyed by size name. */
  borderRadius: Record<string, string>;
  /** Box-shadow tokens, keyed by elevation name. */
  shadows: Record<string, string>;
  /** Responsive breakpoint tokens, keyed by Tailwind breakpoint prefix. */
  breakpoints: Record<string, string>;
}

/**
 * The world-class default token set every FORGE-built project starts from. Colors use the exact
 * shadcn/ui HSL-triplet convention (`H S% L%`, no `hsl()` wrapper — shadcn/ui's own generated
 * `tailwind.config.ts` wraps each value in `hsl(var(--x))` at the point of use) so this default
 * set drops directly into a stock shadcn/ui project with zero translation.
 */
export const DEFAULT_DESIGN_TOKENS: DesignTokens = {
  colors: {
    background: '0 0% 100%',
    foreground: '222.2 84% 4.9%',
    card: '0 0% 100%',
    'card-foreground': '222.2 84% 4.9%',
    primary: '222.2 47.4% 11.2%',
    'primary-foreground': '210 40% 98%',
    secondary: '210 40% 96.1%',
    'secondary-foreground': '222.2 47.4% 11.2%',
    accent: '210 40% 96.1%',
    'accent-foreground': '222.2 47.4% 11.2%',
    muted: '210 40% 96.1%',
    'muted-foreground': '215.4 16.3% 46.9%',
    destructive: '0 84.2% 60.2%',
    'destructive-foreground': '210 40% 98%',
    border: '214.3 31.8% 91.4%',
    input: '214.3 31.8% 91.4%',
    ring: '222.2 84% 4.9%',
  },
  typography: {
    fontFamily: "'Inter', ui-sans-serif, system-ui, -apple-system, sans-serif",
    fontFamilyMono: "'JetBrains Mono', ui-monospace, SFMono-Regular, monospace",
    xs: '0.75rem',
    sm: '0.875rem',
    base: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem',
    weightNormal: '400',
    weightMedium: '500',
    weightSemibold: '600',
    weightBold: '700',
    leadingTight: '1.25',
    leadingNormal: '1.5',
    leadingRelaxed: '1.75',
  },
  spacing: {
    '0': '0px',
    px: '1px',
    '0.5': '0.125rem',
    '1': '0.25rem',
    '1.5': '0.375rem',
    '2': '0.5rem',
    '2.5': '0.625rem',
    '3': '0.75rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '8': '2rem',
    '10': '2.5rem',
    '12': '3rem',
    '16': '4rem',
    '20': '5rem',
    '24': '6rem',
    '32': '8rem',
  },
  borderRadius: {
    sm: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
    inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },
};

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

/** Matches one `--name: value;` CSS custom property declaration inside a `:root`/`.dark` block. */
const CSS_VAR_RE = /--([a-zA-Z0-9-]+)\s*:\s*([^;]+);/g;

/**
 * Extract every `--name: value;` custom property declared in `css` into a flat record, keyed by
 * the property name without its leading `--`. Used against the contents of `globals.css`'s
 * `:root` block; a file with no custom properties (or no file at all) yields `{}`.
 */
function extractCssCustomProperties(css: string): Record<string, string> {
  const found: Record<string, string> = {};
  for (const match of css.matchAll(CSS_VAR_RE)) {
    const name = match[1];
    const value = match[2]?.trim();
    if (name && value !== undefined) found[name] = value;
  }
  return found;
}

/**
 * Extract a bare `fontFamily`/`borderRadius` object literal's string values out of a
 * `tailwind.config.ts` source string by name, using a tolerant regex scan rather than a full
 * TypeScript parse (the config is user-authored and may not even be valid enough to `require`).
 * Returns `{}` when the named key is absent or its value isn't a simple string/array-of-strings.
 */
function extractThemeExtendBlock(source: string, key: string): Record<string, string> {
  const blockMatch = new RegExp(`${key}\\s*:\\s*\\{([\\s\\S]*?)\\}`, 'm').exec(source);
  if (!blockMatch?.[1]) return {};
  const entries: Record<string, string> = {};
  const entryRe = /['"]?([a-zA-Z0-9_-]+)['"]?\s*:\s*(?:\[\s*)?['"]([^'"]+)['"]/g;
  for (const match of blockMatch[1].matchAll(entryRe)) {
    const entryKey = match[1];
    const entryValue = match[2];
    if (entryKey && entryValue !== undefined) entries[entryKey] = entryValue;
  }
  return entries;
}

/** Read a text file, returning `null` on any read failure (missing file, permission error, etc.). */
function readTextFileSafe(filePath: string): string | null {
  try {
    return readFileSync(filePath, 'utf8');
  } catch {
    return null;
  }
}

/**
 * Read `tailwind.config.ts`/`tailwind.config.js` and `globals.css` (checked at their
 * conventional Next.js App Router locations, `src/app/globals.css` then `app/globals.css`) out
 * of `projectPath` and extract whatever design tokens are already configured. Degrades to an
 * empty partial (never throws) when neither file exists or neither contains anything this
 * extractor recognizes — a project with no prior tokens is the expected common case, not an
 * error condition.
 */
export function detectProjectTokens(projectPath: string): Partial<DesignTokens> {
  const detected: Partial<DesignTokens> = {};

  const tailwindConfigPath = ['tailwind.config.ts', 'tailwind.config.js']
    .map((name) => join(projectPath, name))
    .find((candidate) => existsSync(candidate));
  const tailwindSource = tailwindConfigPath ? readTextFileSafe(tailwindConfigPath) : null;
  if (tailwindSource) {
    const fontFamily = extractThemeExtendBlock(tailwindSource, 'fontFamily');
    const borderRadius = extractThemeExtendBlock(tailwindSource, 'borderRadius');
    if (Object.keys(fontFamily).length > 0) {
      detected.typography = { ...(detected.typography ?? {}), ...fontFamily };
    }
    if (Object.keys(borderRadius).length > 0) {
      detected.borderRadius = borderRadius;
    }
  }

  const globalsCssPath = ['src/app/globals.css', 'app/globals.css', 'src/styles/globals.css', 'styles/globals.css']
    .map((relative) => join(projectPath, relative))
    .find((candidate) => existsSync(candidate));
  const cssSource = globalsCssPath ? readTextFileSafe(globalsCssPath) : null;
  if (cssSource) {
    const customProperties = extractCssCustomProperties(cssSource);
    const colorKeys = new Set(Object.keys(DEFAULT_DESIGN_TOKENS.colors));
    const colors: Record<string, string> = {};
    for (const [name, value] of Object.entries(customProperties)) {
      if (colorKeys.has(name)) colors[name] = value;
    }
    if (Object.keys(colors).length > 0) detected.colors = colors;

    const radiusMatch = /--radius\s*:\s*([^;]+);/.exec(cssSource);
    if (radiusMatch?.[1]) {
      detected.borderRadius = { ...(detected.borderRadius ?? {}), md: radiusMatch[1].trim() };
    }
  }

  return detected;
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

/** Render one `key: 'value',`-style line for a Tailwind theme object, indented `indent` spaces. */
function renderThemeEntries(entries: Record<string, string>, indent: number): string {
  const pad = ' '.repeat(indent);
  return Object.entries(entries)
    .map(([key, value]) => `${pad}'${key}': ${JSON.stringify(value)},`)
    .join('\n');
}

/** Render the `colors` block of the Tailwind theme, wrapping each token in `hsl(var(--x))`. */
function renderColorEntries(colors: Record<string, string>, indent: number): string {
  const pad = ' '.repeat(indent);
  return Object.keys(colors)
    .map((key) => `${pad}'${key}': 'hsl(var(--${key}))',`)
    .join('\n');
}

/**
 * Generate a complete `tailwind.config.ts` content string wiring `tokens` into
 * `theme.extend` — colors resolve through CSS custom properties (`hsl(var(--x))`), matching the
 * shadcn/ui convention, so the accompanying `globals.css` (see {@link generateGlobalsCss}) is
 * the single source of truth for the actual color values.
 */
export function generateTailwindConfig(tokens: DesignTokens): string {
  const fontFamilySans = tokens.typography.fontFamily
    ? tokens.typography.fontFamily.split(',').map((part) => part.trim().replace(/^['"]|['"]$/g, ''))
    : ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'];
  const fontFamilyMono = tokens.typography.fontFamilyMono
    ? tokens.typography.fontFamilyMono.split(',').map((part) => part.trim().replace(/^['"]|['"]$/g, ''))
    : ['JetBrains Mono', 'ui-monospace', 'monospace'];

  return `import type { Config } from 'tailwindcss';

/**
 * Generated by FORGE 2.0's DesignTokenManager (src/ui-engine/design-token-manager.ts).
 * Colors resolve through CSS custom properties declared in globals.css so light/dark mode
 * switches by toggling the .dark class alone — no Tailwind config change needed per theme.
 */
const config: Config = {
  darkMode: 'class',
  content: [
    './src/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './pages/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
${renderColorEntries(tokens.colors, 8)}
      },
      fontFamily: {
        sans: ${JSON.stringify(fontFamilySans)},
        mono: ${JSON.stringify(fontFamilyMono)},
      },
      borderRadius: {
${renderThemeEntries(tokens.borderRadius, 8)}
        DEFAULT: 'var(--radius)',
      },
      boxShadow: {
${renderThemeEntries(tokens.shadows, 8)}
      },
      spacing: {
${renderThemeEntries(tokens.spacing, 8)}
      },
      screens: {
${renderThemeEntries(tokens.breakpoints, 8)}
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
`;
}

/** Render one `--name: value;` custom property declaration line, indented `indent` spaces. */
function renderCssVar(name: string, value: string, indent: number): string {
  return `${' '.repeat(indent)}--${name}: ${value};`;
}

/**
 * Darken/lighten heuristic for the `.dark` block: since {@link DEFAULT_DESIGN_TOKENS} ships
 * light-mode HSL triplets, the dark-mode set below is a curated, purpose-built shadcn/ui-style
 * dark palette rather than a mechanical inversion of `tokens.colors` — mechanically flipping
 * lightness alone tends to produce a muddy, low-contrast dark theme, which is explicitly out of
 * bounds for a "world-class default."
 */
const DARK_MODE_COLOR_OVERRIDES: Record<string, string> = {
  background: '222.2 84% 4.9%',
  foreground: '210 40% 98%',
  card: '222.2 84% 4.9%',
  'card-foreground': '210 40% 98%',
  primary: '210 40% 98%',
  'primary-foreground': '222.2 47.4% 11.2%',
  secondary: '217.2 32.6% 17.5%',
  'secondary-foreground': '210 40% 98%',
  accent: '217.2 32.6% 17.5%',
  'accent-foreground': '210 40% 98%',
  muted: '217.2 32.6% 17.5%',
  'muted-foreground': '215 20.2% 65.1%',
  destructive: '0 62.8% 30.6%',
  'destructive-foreground': '210 40% 98%',
  border: '217.2 32.6% 17.5%',
  input: '217.2 32.6% 17.5%',
  ring: '212.7 26.8% 83.9%',
};

/**
 * Generate a complete `globals.css` content string: Tailwind's three base layers, a `:root`
 * block declaring every color token as an HSL-triplet custom property plus `--radius`, and a
 * `.dark` block overriding those same properties for dark mode (Tailwind `darkMode: 'class'`,
 * matching {@link generateTailwindConfig}). Every token from `tokens.colors` gets a light-mode
 * declaration; dark-mode values come from {@link DARK_MODE_COLOR_OVERRIDES} when a curated
 * override exists for that key, else the light-mode value is reused unchanged (never omitted).
 */
export function generateGlobalsCss(tokens: DesignTokens): string {
  const lightVars = Object.entries(tokens.colors)
    .map(([name, value]) => renderCssVar(name, value, 4))
    .join('\n');

  const darkVars = Object.keys(tokens.colors)
    .map((name) => renderCssVar(name, DARK_MODE_COLOR_OVERRIDES[name] ?? tokens.colors[name] ?? '0 0% 0%', 4))
    .join('\n');

  const radius = tokens.borderRadius.md ?? DEFAULT_DESIGN_TOKENS.borderRadius.md;

  return `@tailwind base;
@tailwind components;
@tailwind utilities;

/**
 * Generated by FORGE 2.0's DesignTokenManager (src/ui-engine/design-token-manager.ts).
 * Every value below is an HSL triplet (no hsl() wrapper) consumed via hsl(var(--x)) in
 * tailwind.config.ts, so switching the .dark class is the only thing needed to retheme.
 */
@layer base {
  :root {
${lightVars}
    --radius: ${radius};
  }

  .dark {
${darkVars}
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
    font-family: ${JSON.stringify(tokens.typography.fontFamily ?? DEFAULT_DESIGN_TOKENS.typography.fontFamily)};
  }
}
`;
}

// ---------------------------------------------------------------------------
// Ensure (merge + write)
// ---------------------------------------------------------------------------

/** Shallow-merge two `DesignTokens`-shaped partials bucket-by-bucket (never a deep object merge across buckets). */
function mergeTokens(base: DesignTokens, overrides: Partial<DesignTokens>): DesignTokens {
  return {
    colors: { ...base.colors, ...(overrides.colors ?? {}) },
    typography: { ...base.typography, ...(overrides.typography ?? {}) },
    spacing: { ...base.spacing, ...(overrides.spacing ?? {}) },
    borderRadius: { ...base.borderRadius, ...(overrides.borderRadius ?? {}) },
    shadows: { ...base.shadows, ...(overrides.shadows ?? {}) },
    breakpoints: { ...base.breakpoints, ...(overrides.breakpoints ?? {}) },
  };
}

/** Resolve the conventional `globals.css` write location for a target project: prefers the Next.js App Router path, falls back to the Pages Router path when `src/app`/`app` don't exist yet. */
function resolveGlobalsCssPath(projectPath: string): string {
  if (existsSync(join(projectPath, 'src', 'app'))) return join(projectPath, 'src', 'app', 'globals.css');
  if (existsSync(join(projectPath, 'app'))) return join(projectPath, 'app', 'globals.css');
  return join(projectPath, 'src', 'app', 'globals.css');
}

/**
 * Ensure `projectPath` has a consistent design token set configured: merges `tokens` (a caller
 * override, e.g. from {@link detectProjectTokens} or a project-specific brand) over
 * {@link DEFAULT_DESIGN_TOKENS} bucket-by-bucket, then writes `tailwind.config.ts` and
 * `globals.css` — but ONLY when neither already exists. A project that already configured its
 * own tokens is left completely untouched (never overwritten), matching
 * `ensureComponentsInstalled`'s "skip what's already there" posture in `shadcn-installer.ts`.
 */
export async function ensureDesignTokens(projectPath: string, tokens?: Partial<DesignTokens>): Promise<void> {
  const log = logLine('design-token-manager');
  const merged = mergeTokens(DEFAULT_DESIGN_TOKENS, tokens ?? {});

  const tailwindConfigPath = join(projectPath, 'tailwind.config.ts');
  const tailwindAlreadyConfigured =
    existsSync(tailwindConfigPath) || existsSync(join(projectPath, 'tailwind.config.js'));
  if (tailwindAlreadyConfigured) {
    log(`tailwind.config already present in ${projectPath} — leaving it untouched`);
  } else {
    try {
      mkdirSync(dirname(tailwindConfigPath), { recursive: true });
      writeFileSync(tailwindConfigPath, generateTailwindConfig(merged), 'utf8');
      log(`wrote ${tailwindConfigPath}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      log(`ERROR: failed to write ${tailwindConfigPath}: ${message}`);
    }
  }

  const globalsCssPath = resolveGlobalsCssPath(projectPath);
  if (existsSync(globalsCssPath)) {
    log(`globals.css already present at ${globalsCssPath} — leaving it untouched`);
  } else {
    try {
      mkdirSync(dirname(globalsCssPath), { recursive: true });
      writeFileSync(globalsCssPath, generateGlobalsCss(merged), 'utf8');
      log(`wrote ${globalsCssPath}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      log(`ERROR: failed to write ${globalsCssPath}: ${message}`);
    }
  }
}
