import type { Config } from 'tailwindcss';

/**
 * Generated by FORGE 2.0's DesignTokenManager (src/ui-engine/design-token-manager.ts).
 * Colors resolve through CSS custom properties declared in globals.css so light/dark mode
 * switches by toggling the .dark class alone — no Tailwind config change needed per theme.
 */
const config: Config = {
  darkMode: 'class',
  content: [
    './src/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './pages/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        'background': 'hsl(var(--background))',
        'foreground': 'hsl(var(--foreground))',
        'card': 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        'primary': 'hsl(var(--primary))',
        'primary-foreground': 'hsl(var(--primary-foreground))',
        'secondary': 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        'accent': 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        'muted': 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        'destructive': 'hsl(var(--destructive))',
        'destructive-foreground': 'hsl(var(--destructive-foreground))',
        'border': 'hsl(var(--border))',
        'input': 'hsl(var(--input))',
        'ring': 'hsl(var(--ring))',
      },
      fontFamily: {
        sans: ["Inter","ui-sans-serif","system-ui","-apple-system","sans-serif"],
        mono: ["JetBrains Mono","ui-monospace","SFMono-Regular","monospace"],
      },
      borderRadius: {
        'sm': "0.25rem",
        'md': "0.375rem",
        'lg': "0.5rem",
        'xl': "0.75rem",
        'full': "9999px",
        DEFAULT: 'var(--radius)',
      },
      boxShadow: {
        'sm': "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'md': "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
        'lg': "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
        'xl': "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
        'inner': "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
      },
      spacing: {
        '0': "0px",
        '1': "0.25rem",
        '2': "0.5rem",
        '3': "0.75rem",
        '4': "1rem",
        '5': "1.25rem",
        '6': "1.5rem",
        '8': "2rem",
        '10': "2.5rem",
        '12': "3rem",
        '16': "4rem",
        '20': "5rem",
        '24': "6rem",
        '32': "8rem",
        'px': "1px",
        '0.5': "0.125rem",
        '1.5': "0.375rem",
        '2.5': "0.625rem",
      },
      screens: {
        'sm': "640px",
        'md': "768px",
        'lg': "1024px",
        'xl': "1280px",
        '2xl': "1536px",
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
