#!/usr/bin/env node
/**
 * FORGE 2.0 — Supabase secret generator.
 *
 * Generates a self-consistent set of secrets for the self-hosted Supabase
 * stack: a random HS256 JWT secret plus matching `anon` and `service_role`
 * JWTs signed with it, a Postgres superuser password, dashboard credentials,
 * and the ancillary keys Realtime/Storage/Analytics require.
 *
 * Usage:  node docker/gen-secrets.cjs            (writes docker/.env if absent)
 *         node docker/gen-secrets.cjs --force    (overwrite existing docker/.env)
 *         node docker/gen-secrets.cjs --print    (print to stdout, write nothing)
 *
 * Re-running with --force rotates every secret; you must then recreate the
 * Postgres volume (stop-forge-db.ps1 -Volumes) for the new password to apply.
 */
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const b64url = (b) =>
  Buffer.from(b).toString('base64').replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');

function jwt(payload, secret) {
  const header = b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const body = b64url(JSON.stringify(payload));
  const data = `${header}.${body}`;
  const sig = crypto.createHmac('sha256', secret).update(data).digest();
  return `${data}.${b64url(sig)}`;
}

// URL-safe alphanumeric token of length n.
const token = (n) =>
  crypto.randomBytes(n * 2).toString('base64').replace(/[^a-zA-Z0-9]/g, '').slice(0, n);

function generate() {
  const jwtSecret = token(48);
  // Fixed issue time + 10y expiry. Date.now() is intentionally avoided so the
  // generator is deterministic to invoke; token lifetime is effectively
  // perpetual for a local single-operator dev database.
  const iat = 1718000000;
  const exp = iat + 60 * 60 * 24 * 365 * 10;
  return {
    POSTGRES_PASSWORD: token(32),
    JWT_SECRET: jwtSecret,
    ANON_KEY: jwt({ role: 'anon', iss: 'supabase', iat, exp }, jwtSecret),
    SERVICE_ROLE_KEY: jwt({ role: 'service_role', iss: 'supabase', iat, exp }, jwtSecret),
    DASHBOARD_USERNAME: 'forge',
    DASHBOARD_PASSWORD: token(24),
    SECRET_KEY_BASE: token(64),
    VAULT_ENC_KEY: token(32),
    LOGFLARE_API_KEY: token(32),
  };
}

function toEnv(secrets) {
  return (
    [
      '# FORGE 2.0 — Supabase self-hosting secrets (generated by gen-secrets.cjs).',
      '# DO NOT COMMIT. This file is consumed by docker-compose.yml.',
      '# The ANON_KEY and SERVICE_ROLE_KEY are HS256 JWTs signed with JWT_SECRET —',
      '# regenerating JWT_SECRET invalidates both keys, so rotate them together.',
      '',
      ...Object.entries(secrets).map(([k, v]) => `${k}=${v}`),
      '',
    ].join('\n')
  );
}

function main() {
  const args = process.argv.slice(2);
  const envPath = path.join(__dirname, '.env');
  const secrets = generate();

  if (args.includes('--print')) {
    process.stdout.write(toEnv(secrets));
    return;
  }
  if (fs.existsSync(envPath) && !args.includes('--force')) {
    process.stdout.write(`docker/.env already exists — leaving it untouched.\n`);
    process.stdout.write(`Pass --force to rotate secrets, or --print to preview.\n`);
    return;
  }
  fs.writeFileSync(envPath, toEnv(secrets), { mode: 0o600 });
  process.stdout.write(`Wrote ${envPath}\n`);
  process.stdout.write(`FORGE_SUPABASE_ANON_KEY=${secrets.ANON_KEY}\n`);
  process.stdout.write(`FORGE_SUPABASE_SERVICE_KEY=${secrets.SERVICE_ROLE_KEY}\n`);
}

main();
