/**
 * FORGE 2.0 — System 1: RegenerationEngine (src/resurrection/regeneration-engine.ts).
 *
 * The ONLY System 1 component that writes to a governance file. Acts strictly on the tier
 * `ArtifactHealthScorer` already assigned (never re-evaluates severity — R4) and refuses to
 * write while the project has an in-flight Phase 3 build (Contract R-2 / Contract 3).
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { getBuildsByProject } from '../memory/builds.js';
import { runClaude } from '../engine/claude-runner.js';
import { findGovernanceDoc } from './governance-gaps.js';
import { scoreArtifact } from './artifact-scorer.js';
import type { ArtifactScore, DriftDetail, RegenResult } from './types.js';
import { ARTIFACT_FILENAMES, SECTION_SCOPED_ARTIFACTS, WHOLESALE_ARTIFACTS } from './types.js';
import type { ScanReport } from '../retrofit/types.js';
import type { ArtifactName } from './types.js';

const NON_TERMINAL_BUILD_STATUSES = new Set(['queued', 'running']);

/** Contract R-2 guard: refuse to write while the project has a build in flight. */
export async function isBuildInFlight(projectName: string): Promise<boolean> {
  const builds = await getBuildsByProject(projectName);
  if (!builds) return false;
  return builds.some((b) => NON_TERMINAL_BUILD_STATUSES.has(b.status));
}

/** Section-scoped content is drafted through the Claude Code CLI (BLUEPRINT §RegenerationEngine
 * "Claude for regeneration content" — same runner Phase 2 governance generation uses, never a
 * direct Anthropic API call). */
async function draftSectionContent(
  artifact: ArtifactName,
  section: string,
  gapContext: string,
  projectPath: string
): Promise<string> {
  const prompt =
    `Write the Markdown body (no "## ${section}" header, just the content) for the ` +
    `"${section}" section of a ${artifact}.md governance document. Base it strictly on ` +
    `this real project context — do not invent facts:\n\n${gapContext}\n\n` +
    'Respond with only the Markdown body, no preamble.';
  const result = await runClaude(prompt, { cwd: projectPath, timeoutMs: 5 * 60 * 1000 });
  const text = result.stdout.trim();
  if (result.success && text) return text;
  return `_Reconstructed by FORGE's RegenerationEngine from live codebase state:_\n\n${gapContext}`;
}

function patchSectionScoped(content: string, section: string, body: string): string {
  const headerRe = new RegExp(`^##\\s+${section.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*$`, 'm');
  const match = headerRe.exec(content);
  if (!match) {
    // Section absent entirely — append it at the end.
    return `${content.trimEnd()}\n\n## ${section}\n\n${body}\n`;
  }
  const start = match.index + match[0].length;
  const rest = content.slice(start);
  const nextHeaderMatch = /^##\s+/m.exec(rest.slice(1));
  const end = nextHeaderMatch ? start + 1 + nextHeaderMatch.index : content.length;
  return `${content.slice(0, start)}\n\n${body}\n\n${content.slice(end)}`.replace(/\n{4,}/g, '\n\n\n');
}

/** Deterministic wholesale render for SESSION_STATE/STATE_OF_THE_BUILD/TOOLCHAIN from real state. */
function renderWholesale(artifact: ArtifactName, projectName: string, scanReport: ScanReport | null): string {
  const lines: string[] = [`# ${projectName} — ${artifact.replace(/_/g, ' ')}`, ''];
  lines.push(`> Regenerated by FORGE 2.0 RegenerationEngine on ${new Date().toISOString()}.`, '');
  if (artifact === 'SESSION_STATE') {
    lines.push('## Active Build', '', '(no build currently in flight — regenerated between phases)', '');
    lines.push('## IDE STATUS', '', '- Regenerated by System 1 gap audit.', '');
    lines.push('## Notes', '', 'This document was auto-regenerated after a governance gap audit found it below the AUTO threshold.', '');
  } else if (artifact === 'STATE_OF_THE_BUILD') {
    lines.push('## Phase Status', '', 'Reconstructed from the most recent gap audit — see .forge/gap_audit_report.md.', '');
    lines.push('## Design Summary', '', '(regenerated placeholder-free from live scan — refine with project specifics as the build continues)', '');
    lines.push('## Governance Package', '', scanReport ? scanReport.governanceInventory.map((g) => `- ${g.filename}: ${g.staleness}`).join('\n') : '(no scan data available)', '');
    lines.push('## Codebase Audit', '', scanReport ? `${scanReport.fileTree.totalFiles} files, ${scanReport.brokenImports.length} broken imports, ${scanReport.compilationErrors.length} TS errors.` : '(no scan data available)', '');
    lines.push('## Next Step', '', 'Re-run `forge audit` to confirm the regeneration cleared the reported gaps.', '');
  } else if (artifact === 'TOOLCHAIN') {
    lines.push('## Detected Stack', '', '(regenerated from the latest scan — see .forge/scan_report.json for full detail)', '');
    lines.push('## Locked Tool Versions', '');
    if (scanReport) {
      lines.push('| Tool | Required | Status | Version / Path |', '|------|----------|--------|----------------|');
      for (const p of scanReport.packageAudit) lines.push(`| ${p.name} | — | ${p.issue} | ${p.currentVersion ?? 'unknown'} |`);
    }
    lines.push('', '## Skill Manifest', '', '(unchanged — regeneration does not alter skill wiring)', '');
    lines.push('## Environment Variable Checklist', '', scanReport ? scanReport.envAudit.map((e) => `- ${e.name}: ${e.classification}`).join('\n') : '(no scan data)', '');
    lines.push('## Docker / Build Memory', '', '(unchanged)', '');
    lines.push('## Blockers', '', '(none recorded by this regeneration pass)', '');
  }
  return lines.join('\n');
}

export interface RegenerateInput {
  projectPath: string;
  projectName: string;
  artifact: ArtifactName;
  score: ArtifactScore;
  scanReport: ScanReport | null;
  gapAuditRunId: string;
  allDocs: Partial<Record<ArtifactName, string>>;
  /** Set true when this artifact reached AUTO status via a human-approved gate, not the tier itself. */
  humanApproved?: boolean;
}

/** Regenerate exactly one artifact. Never re-evaluates tier — acts only on what was passed in. */
export async function regenerate(input: RegenerateInput): Promise<RegenResult> {
  const { projectPath, projectName, artifact, score, scanReport, gapAuditRunId, allDocs, humanApproved } = input;
  const healthScoreBefore = score.composite_score;

  if (score.regeneration_tier !== 'AUTO' && !humanApproved) {
    return { artifact, attempted: false, wrote: false, reason: 'not AUTO tier and not human-approved', healthScoreBefore, healthScoreAfter: null };
  }

  if (await isBuildInFlight(projectName)) {
    return {
      artifact,
      attempted: true,
      wrote: false,
      reason: 'refused — project has an in-flight Phase 3 build (Contract 3 / Contract R-2)',
      healthScoreBefore,
      healthScoreAfter: null,
    };
  }

  const filename = ARTIFACT_FILENAMES[artifact];
  const targetPath = join(projectPath, filename);
  let newContent: string;

  if (WHOLESALE_ARTIFACTS.includes(artifact)) {
    newContent = renderWholesale(artifact, projectName, scanReport);
  } else if (SECTION_SCOPED_ARTIFACTS.includes(artifact)) {
    const doc = findGovernanceDoc(projectPath, artifact);
    let content = doc?.content ?? `# ${projectName} — ${artifact.replace(/_/g, ' ')}\n`;
    for (const section of score.missing_sections) {
      const gapContext = describeDrift(artifact, section, score.drift_detail);
      const body = await draftSectionContent(artifact, section, gapContext, projectPath);
      content = patchSectionScoped(content, section, body);
    }
    for (const drift of score.drift_detail ?? []) {
      const body = await draftSectionContent(artifact, drift.section, `Drift detected: doc says "${drift.docSays}", code shows "${drift.codeShows}".`, projectPath);
      content = patchSectionScoped(content, drift.section, appendUnique(extractSectionBody(content, drift.section), body));
    }
    newContent = content;
  } else {
    return { artifact, attempted: true, wrote: false, reason: 'artifact not in wholesale or section-scoped lists', healthScoreBefore, healthScoreAfter: null };
  }

  try {
    writeFileSync(targetPath, newContent, 'utf8');
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    return { artifact, attempted: true, wrote: false, reason: `write failed: ${detail}`, healthScoreBefore, healthScoreAfter: null };
  }

  const rescored = await scoreArtifact({
    projectPath,
    artifact,
    gapAuditRunId,
    scanReport,
    allDocs: { ...allDocs, [artifact]: newContent },
  });
  const healthScoreAfter = rescored.score.composite_score;

  if (healthScoreAfter <= healthScoreBefore) {
    return {
      artifact,
      attempted: true,
      wrote: true,
      reason: 'regeneration wrote a new file but health_score_after did not improve — reported as failed (Iron Law 3)',
      healthScoreBefore,
      healthScoreAfter,
    };
  }

  return { artifact, attempted: true, wrote: true, healthScoreBefore, healthScoreAfter };
}

function describeDrift(artifact: ArtifactName, section: string, drift: DriftDetail[] | null): string {
  const relevant = (drift ?? []).filter((d) => d.section === section);
  if (relevant.length === 0) return `Missing required section "${section}" in ${artifact}.`;
  return relevant.map((d) => `Code shows: ${d.codeShows} (doc previously said: ${d.docSays})`).join('\n');
}

function extractSectionBody(content: string, section: string): string {
  const headerRe = new RegExp(`^##\\s+${section.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*$`, 'm');
  const match = headerRe.exec(content);
  if (!match) return '';
  const start = match.index + match[0].length;
  const rest = content.slice(start);
  const nextHeaderMatch = /^##\s+/m.exec(rest.slice(1));
  const end = nextHeaderMatch ? start + 1 + nextHeaderMatch.index : content.length;
  return content.slice(start, end).trim();
}

function appendUnique(existing: string, addition: string): string {
  if (existing.includes(addition)) return existing;
  return `${existing}\n\n${addition}`.trim();
}

export interface RegenerateAllInput {
  projectPath: string;
  projectName: string;
  scores: ArtifactScore[];
  scanReport: ScanReport | null;
  gapAuditRunId: string;
  allDocs: Partial<Record<ArtifactName, string>>;
  /** Artifacts a human approved via HumanGateEvaluator, to run through this same engine. */
  humanApprovedArtifacts?: ArtifactName[];
}

export async function regenerateAll(input: RegenerateAllInput): Promise<RegenResult[]> {
  const approved = new Set(input.humanApprovedArtifacts ?? []);
  const results: RegenResult[] = [];
  for (const score of input.scores) {
    if (score.regeneration_tier !== 'AUTO' && !approved.has(score.artifact_name)) continue;
    const result = await regenerate({
      projectPath: input.projectPath,
      projectName: input.projectName,
      artifact: score.artifact_name,
      score,
      scanReport: input.scanReport,
      gapAuditRunId: input.gapAuditRunId,
      allDocs: input.allDocs,
      humanApproved: approved.has(score.artifact_name),
    });
    results.push(result);
  }
  return results;
}
